### ISSUE TITLE
url-retrieve-synchronously buffers proliferate

### ISSUE THREAD

**Issue by jashank** [abrochard/emacs-todoist#13]
I started using todoist.el yesterday --- I love it already --- but this morning I find I have twenty or thirty buried 55kB buffers hanging around that were spawned by (I assume) `url-retrieve-synchronously` in `todoist--query`. is it possible to get rid of those buffers automatically?

**Comment by abrochard** [comment]
Thank you! I'm glad you like it.
I will look into this. You are probably right, they must be leftovers from the query call, and it should be fairly easily to kill them once they are parsed.

**Comment by abrochard** [comment]
Hi @jashank , I tried to reproduce this the other day but I was unable to find the buffers you are talking about. What are they called? 

Here are my steps:
1. start with a fresh emacs instance
2. open buffer list with `C-x C-b`
3. summon todoist with `M-x todoist`
4. refresh the buffer list 
5. no new buffer appeared aside from the `*todoist*` one

I repeated step 3 and still saw nothing.

**Comment by jashank** [comment]
(My apologies for the extremely long gap, and for digging up a timed-out issue.)

The buffers in question won't appear in a normal `list-buffers` call ---

> `list-buffers` omits buffers whose names begin with a space, unless they visit files: such buffers are used internally by Emacs. 
> --- <https://www.gnu.org/software/emacs/manual/html_node/emacs/List-Buffers.html>

These buffers _do_ appear if we look directly.  In a clean `emacs -Q`, into which I've only poked my Todoist token, here's an extract from a lisp-interaction:

``` elisp
(emacs-version)
;; ==> "GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
;;      of 2019-08-30"

(load-file "~/.emacs.d/elpa/dash-20200119.2310/dash.el")
;; ==> t
(load-file "~/.emacs.d/elpa/transient-20200125.1308/transient.el")
;; ==> t
(load-file "~/.emacs.d/elpa/todoist-20191014.2033/todoist.el")
;; ==> t

(defun list-buffer-names ()
  (mapcar
   (lambda (buff) (buffer-name buff))
   (buffer-list (selected-frame))))
;; ==> list-buffer-names


(setq buffers-a (list-buffer-names))
;; ==> ("todoist-leaks-buffers.el" " *Minibuf-1*" "*scratch*"
;;      " *Minibuf-0*" "*Messages*" " *code-conversion-work*"
;;      " *Echo Area 0*" " *Echo Area 1*" "*Completions*")

(todoist)
;; ==> nil

(setq buffers-b (list-buffer-names))
;; ==> ("todoist-leaks-buffers.el" " *Minibuf-1*" "*todoist*"
;;      "*scratch*" " *Minibuf-0*" "*Messages*"
;;      " *code-conversion-work*" " *Echo Area 0*" " *Echo Area 1*"
;;      " *http api.todoist.com:443*"
;;      " *http api.todoist.com:443*-880941"
;;      " *http api.todoist.com:443*-443961" ...)

(cl-set-difference buffers-b buffers-a)
;; ==> ("*todoist*" " *http api.todoist.com:443*"
;;      " *http api.todoist.com:443*-880941"
;;      " *http api.todoist.com:443*-443961")

(todoist)
;; ==> nil

(setq buffers-c (list-buffer-names))
;; ==> ("todoist-leaks-buffers.el" "*todoist*" " *Minibuf-1*"
;;      "*scratch*" " *Minibuf-0*" "*Messages*"
;;      " *code-conversion-work*" " *Echo Area 0*" " *Echo Area 1*"
;;      " *http api.todoist.com:443*"
;;      " *http api.todoist.com:443*-880941"
;;      " *http api.todoist.com:443*-443961" ...)

(cl-set-difference buffers-c buffers-b)
;; ==> (" *http api.todoist.com:443*-65848"
;;      " *http api.todoist.com:443*-159589")

(cl-set-difference buffers-c buffers-a)
;; ==> ("*todoist*" " *http api.todoist.com:443*"
;;      " *http api.todoist.com:443*-880941"
;;      " *http api.todoist.com:443*-443961"
;;      " *http api.todoist.com:443*-65848"
;;      " *http api.todoist.com:443*-159589")


```

Using tools like ido, helm, etc., to list or switch buffers makes this more apparent: they don't (by default?) skip buffers according to this rule.

**Comment by abrochard** [comment]
Oh. That makes sense. I didn't know about this list buffer behavior. Thank you for coming back with this and for providing such details. I will look into it.
