### ISSUE TITLE
completed tasks needed

### ISSUE THREAD

**Issue by jinlin82** [abrochard/emacs-todoist#16]
How can I get the completed tasks into the buffer? 

Thank you!

**Comment by abrochard** [comment]
Hi @jinlin82 , 
Thank you for your interest.
Unfortunately at this time the [todoist api](https://developer.todoist.com/rest/v1/#get-active-tasks) does not let me get the list of completed tasks. 
What I may suggest is to maybe use a service like [IFTTT](https://ifttt.com/todoist) to connect todoist to another service? In the past I used to it to have my completed tasks added to a google sheets document. Not sure if that still exists.
