### ISSUE TITLE
accented letters in todoist are garbled

### ISSUE THREAD

**Issue by brandelune** [abrochard/emacs-todoist#2]
For ex, "Écrire" in todoist becomes "Ã\211crire" in emacs. There must be an encoding issue somewhere.

**Comment by cybniv** [comment]
can confirm, same with umlauts.
``miete überweisen`` becomes ``miete Ã¼berweisen``. 

this usually happens if source is UTF-8, but somehow it gets interpreted as ISO 8859-1 (Latin-1).

**Comment by abrochard** [comment]
Thanks for reporting this. I am a noob about encoding but will take a look. Any help is welcome.

**Comment by brandelune** [comment]
I'm a noob about elisp, but if you can force the strings to be kept in utf-8 all the way you'll make it. Btw, it's really nice the way you implemented the thing as an org-mode file. Truly excellent work ! :-)

**Comment by abrochard** [comment]
Thank you so much! Glad you like it.
I just pushed something that decodes the HTTP response as UTF8 and it worked with `Écrire`. Give it a few hours for Melpa to build and give it a shot?

**Comment by brandelune** [comment]
Excellent ! It even works with Japanese, so I think you got everything covered. I guess you can close now :)

**Comment by abrochard** [comment]
Awesome! Let me know if anything else comes up.
