### ISSUE TITLE
Load it up via Elisp?

### ISSUE THREAD

**Issue by james-york** [abrochard/emacs-todoist#20]
This looks great!
But, I'm a massive newb when it comes to emacs. What does step 3 mean in your install guide?

> 3. Load it up via
> a. Elisp (setq todoist-token "XXXXXXXXXXXXXXXXXXXX")
> b. Environment variable as TODOIST_TOKEN

**Comment by abrochard** [comment]
Hi @james-york , welcome to Emacs!

Step 3 essentially means "assign the variable `todoist-token` to the value of the token you grabbed from from step 2".

The easiest way to do that is to go to your scratch buffer and paste that line
```
(setq todoist-token "XXXXXXXXXXXXXXXXXXXX")
```
where the `XXXX..` is replaced by your token from step 2.
Then put your cursor after the closing `)` parenthesis and press `C-x C-e` (control + x, control + e).

And that's it! The value is loaded into Emacs for this session. Now if you want the change to be automatic and permanent, you can just paste that line into your config file (.emacs or whatever you use) and it will be picked up at Emacs startup. 

Just make sure that you don't share that token publicly as it gives access to your todoist account.

Let me know if you are still having trouble after this and feel free to re-open this issue.
