### ISSUE TITLE
No catch for tag: bad-response Bad status code returned: 400

### ISSUE THREAD

**Issue by slondr** [abrochard/emacs-todoist#21]
I get this every time I run M-x todoist all of a sudden

**Comment by abrochard** [comment]
400 means authentication generally. Are you sure that your token is still valid?

**Comment by slondr** [comment]
My token hasn't changed in the Integrations page, so I assume it is.

**Comment by abrochard** [comment]
Can you try rotating your token?

**Comment by slondr** [comment]
> Can you try rotating your token?

That worked, thanks!
