### ISSUE TITLE
todoist--query results in 400 response

### ISSUE THREAD

**Issue by mnazaal** [abrochard/emacs-todoist#22]
Hi,
I just installed this package and I'm getting the following error when using the package, whether its about creating a new task, updating, deleting etc

```
Contacting host: api.todoist.com:443
todoist--query: No catch for tag: bad-response, "Bad status code returned: 400"
```

I installed the package with MELPA, then tried with loading the token from both the config file itself and as an env variable

**Comment by abrochard** [comment]
Hi @mnazaal,
A 400 generally means something is wrong with the token. Do you have the capacity to test the token directly by calling the API yourself? 
https://developer.todoist.com/rest/v1/#getting-started

**Comment by mnazaal** [comment]
Thanks - it was a parentheses mismatch!

**Comment by abrochard** [comment]
Hey @mnazaal , could you share how you fixed it? Was your token invalid?

**Comment by mnazaal** [comment]
Hey, just updated the previous to reflect that - thanks again
