### ISSUE TITLE
Make Todoist buffer visible to Org agenda

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [abrochard/emacs-todoist#3]
If you give `*todoist*` a backing buffer, then it would be possible to read it and add it to custom agenda views.

**Comment by abrochard** [comment]
Sounds like a good idea. I will probably make a `todoist-backing-buffer` variable which could be used to determine the file location of that backing buffer. But to be clear this file would get overwritten by whatever is pulled from todoist, it would not be a two way sync.

**Comment by matthew-piziak** [comment]
Yes, I think that would be perfectly honest!

**Comment by abrochard** [comment]
Done as part of https://github.com/abrochard/emacs-todoist/commit/cddd0c8a8c50d8767736c0c412070f1fd84c7f4b
