### ISSUE TITLE
Todoist API version update needed before Nov 30

### ISSUE THREAD

**Issue by Schnouki** [abrochard/emacs-todoist#34]
Hey there,

I'm a software engineer at Doist, working on the Todoist backend. I'm also a long-time Emacs user. Yes, parts of Todoist are written in Emacs 😊

I just wanted to let you know that the API you're currently using (REST API v1) is deprecated and will be removed on Nov 30. You should upgrade to REST API v2 before that date to ensure everything keeps working for your users.
All differences are listed in the [migration guide](https://developer.todoist.com/rest/v2/#migrating-from-v1); mostly, a few fields are renamed, and all IDs are now strings instead of integers. I just had a very quick look at your code, and it looks to me that in your case, updating the base URL should be enough 🙂

Could you please consider doing this before Nov 30?

Thanks!

**Comment by abrochard** [comment]
Hi!
Thank you for bringing this to my attention. I update the `todoist-url` to point to v2 and did a quick code review and test on local and it seems to work!
I will merge that soon.
