### ISSUE TITLE
Allow refiling Todoist tasks

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [abrochard/emacs-todoist#4]
It would be nice to be able to refile Todoist tasks to a persisted Org buffer while simultaneously closing the task.

**Comment by abrochard** [comment]
I'm not 100% sure what kind of behavior you would like. You would close the todoist task and as it is removed from your todoist list, you would want an "archived" copy to go to a file?

**Comment by matthew-piziak** [comment]
Right! Good question, I wasn't clear. What I want is the ability to _move_ (refile) tasks from *todoist* to somewhere else. That is, the task should now be in the new location (the refile target), while being absent from the old location (Todoist).

So properly, I should not have said "close". To have move semantics, it should be _deleted_ from Todoist while being refiled to the new location.

Does that make more sense?

**Comment by abrochard** [comment]
I see. So you essentially want the ability to move a task from todoist to another org location, and delete it from todoist server. Am I correct? I'm not super familiar with refiling tasks across multiple files so I'll experiment first but it should be doable.

**Comment by matthew-piziak** [comment]
Yep, that'e exactly right. Thank you! Org makes it pretty simple to refile across files and headers anywhere in `org-refile-targets`.

**Comment by abrochard** [comment]
Closed by #27
