### ISSUE TITLE
Feature Request: Be able to mark tasks as completed not today, but on a certain date in the past

### ISSUE THREAD

**Issue by androclus** [abrochard/emacs-todoist#40]
First: Thank you for Todoist! I love a lot about it -- even in web browser, key shortcuts work. API as well (Emacs). English language dating for tasks, and more.

Second, please forgive me if the following feature request is a FAQ or a subject that has been beaten to death and has already been decided for some good reason not to include...

**FEATURE**

It would be nice for various reasons to be able to mark a task completed, not just Today, but Yesterday or at some previous date.

**DISCUSSIONS**

I see that it has been discussed multiple times on reddit for years. Here are two, for instance:

- https://www.reddit.com/r/todoist/comments/uprwyl/completed_a_task_yesterday_but_forgot_to_check_it/
- https://www.reddit.com/r/todoist/comments/5keexb/mark_a_recurring_task_completed_yesterday/
- and so on..

**EXAMPLE USE-CASE**

I like to review what I got done yesterday, over the last week, and last month. Both for one-off tasks, and for recurring tasks.

So for instance: Perhaps I forgot to mark yesterday when I completed a recurring task (like reviewing our department's expenditures weekly). But now it is today (a day later), and I'd like to be able to go back in and mark retroactively that I DID do that recurring task YESTERDAY.

This is so that -- even days later -- I can go back and correct things I forgot to mark so that my Todoist Completed list (and any Sync'd Calendars!) accurately reflects what I did do on any particular day.

**ADDITIONAL COMMENTS**

I don't really understand why this functionality has not been added, and **long ago**. I am probably missing something obvious, or focused only on my own needs :-) but really, it seems to me that after 16+ years of working on Todoist, this would have been something done in the very first year.

I mean, the way it is now, my boss may ask, "Why didn't you review weekly dept expenditures last Monday?", and she is only mistaken because actually I **DID** do it, but now I cannot go back and mark it done for last Monday retroactively.

Again, thank you all for the great work, and otherwise, I love Todoist, and am a paid subscriber and use it daily.

**Comment by abrochard** [comment]
Hi!
Thank you for the kind words.
I do like the idea too, unfortunately I do not think the [API supports it](https://developer.todoist.com/rest/v2/#update-a-task) as the operation is just "close a task" and doesn't allow a date to be passed.
If this were to become an official feature supported by todoist and exposed in the API, I agree that it would be a good addition to this extension implementation.
(Also to be clear, I'm not employed/contracted/affiliated with todoist and I cannot influence their roadmap)

**Comment by Lillenne** [comment]
@androclus this behavior is supported via the Todoist sync API and is implemented for non-recurring tasks in my project [org-todoist](https://github.com/Lillenne/org-todoist)!
