### ISSUE TITLE
Unable to create a task under a project outside of Inbox

### ISSUE THREAD

**Issue by ataylor-us** [abrochard/emacs-todoist#41]
I could be doing this wrong--I'm a bit rusty with emacs, and new to todoist, but I can't seem to be able to create a new task under a project outside of Inbox.  All tasks created with`M-x todoist-new-task` go just right into `Inbox`, without prompting for a project.  I'm not sure if this is just user error on my part though, would you be able to confirm that this feature still works when you have time?  Furthermore, `M-x todoist-quick-new-task` seems to do the same thing as `M-x todoist-new-task`.

Using Doom Emacs, Emacs 29.1 on a Mac.  Thanks!

**Comment by abrochard** [comment]
Hi @alpacathunder1 ,

The feature is actually poorly documented (and it would be a sweet PR to add it in the README) but you can create new tasks under a specific project by using the `C-u` modifier before calling `todoist-new-task` or `todoist-quick-new-task`. So if you do `C-u M-x todoist-new-task`, you will be prompted to select a project to file the new task under.

Hope this helps!
