### ISSUE TITLE
Do not collapse Org structure after deleting task

### ISSUE THREAD

**Issue by matthew-piziak** [abrochard/emacs-todoist#7]
After deleting task, it's probably a good idea to keep the header structure open. Right now it collapses everything, so if you're working with multiple tasks it's a bit frustrating.

**Comment by abrochard** [comment]
That's actually a bit difficult to do because whenever you close a task I pull down the data from todoist and do a complete buffer refresh. This is why it seems that everything is collapsing. Not really sure how to address that cleanly.

**Comment by matthew-piziak** [comment]
Ah, okay! I can see that remembering the outline state could be difficult. As a partial solution, how about a variable that allows me to chose between collapsed-by-default or expanded-by-default? I wouldn't mind having everything fully expanded all the time, since I usually refile tasks pretty quickly. Then it would be a matter of running a function on the `*todoist*` buffer on refresh. That would be `(hide-sublevels 1)` for collapsed (equivalent to the current behavior), or `outline-show-all` for expansion.

**Comment by abrochard** [comment]
That sounds fair. So something like `todoist-show-all` default to nil, and if not nil shows all tasks?

**Comment by matthew-piziak** [comment]
@abrochard Yes, exactly. :)

**Comment by abrochard** [comment]
done as part of https://github.com/abrochard/emacs-todoist/commit/295691b47a259dc5297e90d916e25847aec15cb0
